//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrCMS.Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sponsordata", Namespace="http://www.matontine.online:82/")]
    [System.SerializableAttribute()]
    public partial class sponsordata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sponsoridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondarySponsorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string occupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phonenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        private bool addonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicynumberField;
        
        private int InstalmentField;
        
        private System.Nullable<System.DateTime> SponsorStartDateField;
        
        private System.Nullable<System.DateTime> PolicyStartDateField;
        
        private System.Nullable<System.DateTime> PolicyEndDateField;
        
        private int PolicynotificationconfigField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sponsorid {
            get {
                return this.sponsoridField;
            }
            set {
                if ((object.ReferenceEquals(this.sponsoridField, value) != true)) {
                    this.sponsoridField = value;
                    this.RaisePropertyChanged("sponsorid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullnameField, value) != true)) {
                    this.fullnameField = value;
                    this.RaisePropertyChanged("fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SecondarySponsor {
            get {
                return this.SecondarySponsorField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondarySponsorField, value) != true)) {
                    this.SecondarySponsorField = value;
                    this.RaisePropertyChanged("SecondarySponsor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.zipcodeField, value) != true)) {
                    this.zipcodeField = value;
                    this.RaisePropertyChanged("zipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string occupation {
            get {
                return this.occupationField;
            }
            set {
                if ((object.ReferenceEquals(this.occupationField, value) != true)) {
                    this.occupationField = value;
                    this.RaisePropertyChanged("occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phonenumberField, value) != true)) {
                    this.phonenumberField = value;
                    this.RaisePropertyChanged("phonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool addon {
            get {
                return this.addonField;
            }
            set {
                if ((this.addonField.Equals(value) != true)) {
                    this.addonField = value;
                    this.RaisePropertyChanged("addon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Policynumber {
            get {
                return this.PolicynumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicynumberField, value) != true)) {
                    this.PolicynumberField = value;
                    this.RaisePropertyChanged("Policynumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int Instalment {
            get {
                return this.InstalmentField;
            }
            set {
                if ((this.InstalmentField.Equals(value) != true)) {
                    this.InstalmentField = value;
                    this.RaisePropertyChanged("Instalment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<System.DateTime> SponsorStartDate {
            get {
                return this.SponsorStartDateField;
            }
            set {
                if ((this.SponsorStartDateField.Equals(value) != true)) {
                    this.SponsorStartDateField = value;
                    this.RaisePropertyChanged("SponsorStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> PolicyStartDate {
            get {
                return this.PolicyStartDateField;
            }
            set {
                if ((this.PolicyStartDateField.Equals(value) != true)) {
                    this.PolicyStartDateField = value;
                    this.RaisePropertyChanged("PolicyStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<System.DateTime> PolicyEndDate {
            get {
                return this.PolicyEndDateField;
            }
            set {
                if ((this.PolicyEndDateField.Equals(value) != true)) {
                    this.PolicyEndDateField = value;
                    this.RaisePropertyChanged("PolicyEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int Policynotificationconfig {
            get {
                return this.PolicynotificationconfigField;
            }
            set {
                if ((this.PolicynotificationconfigField.Equals(value) != true)) {
                    this.PolicynotificationconfigField = value;
                    this.RaisePropertyChanged("Policynotificationconfig");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBeneficiarydata", Namespace="http://www.matontine.online:82/", ItemName="beneficiarydata")]
    [System.SerializableAttribute()]
    public class ArrayOfBeneficiarydata : System.Collections.Generic.List<MrCMS.Web.ServiceReference1.beneficiarydata> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="beneficiarydata", Namespace="http://www.matontine.online:82/")]
    [System.SerializableAttribute()]
    public partial class beneficiarydata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sponsoridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string beneficiaryidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullnameField;
        
        private System.Nullable<System.DateTime> dateofbirthField;
        
        private System.Nullable<System.DateTime> BeneficiaryStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string relationshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phonenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lgaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guardianphoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guardianemailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suggestedproviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suggestedplanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicynumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        private bool VerificationStatusField;
        
        private bool addonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sponsorid {
            get {
                return this.sponsoridField;
            }
            set {
                if ((object.ReferenceEquals(this.sponsoridField, value) != true)) {
                    this.sponsoridField = value;
                    this.RaisePropertyChanged("sponsorid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string beneficiaryid {
            get {
                return this.beneficiaryidField;
            }
            set {
                if ((object.ReferenceEquals(this.beneficiaryidField, value) != true)) {
                    this.beneficiaryidField = value;
                    this.RaisePropertyChanged("beneficiaryid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullnameField, value) != true)) {
                    this.fullnameField = value;
                    this.RaisePropertyChanged("fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> dateofbirth {
            get {
                return this.dateofbirthField;
            }
            set {
                if ((this.dateofbirthField.Equals(value) != true)) {
                    this.dateofbirthField = value;
                    this.RaisePropertyChanged("dateofbirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> BeneficiaryStartDate {
            get {
                return this.BeneficiaryStartDateField;
            }
            set {
                if ((this.BeneficiaryStartDateField.Equals(value) != true)) {
                    this.BeneficiaryStartDateField = value;
                    this.RaisePropertyChanged("BeneficiaryStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string relationship {
            get {
                return this.relationshipField;
            }
            set {
                if ((object.ReferenceEquals(this.relationshipField, value) != true)) {
                    this.relationshipField = value;
                    this.RaisePropertyChanged("relationship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phonenumberField, value) != true)) {
                    this.phonenumberField = value;
                    this.RaisePropertyChanged("phonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string lga {
            get {
                return this.lgaField;
            }
            set {
                if ((object.ReferenceEquals(this.lgaField, value) != true)) {
                    this.lgaField = value;
                    this.RaisePropertyChanged("lga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string guardianphone {
            get {
                return this.guardianphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.guardianphoneField, value) != true)) {
                    this.guardianphoneField = value;
                    this.RaisePropertyChanged("guardianphone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string guardianemail {
            get {
                return this.guardianemailField;
            }
            set {
                if ((object.ReferenceEquals(this.guardianemailField, value) != true)) {
                    this.guardianemailField = value;
                    this.RaisePropertyChanged("guardianemail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string suggestedprovider {
            get {
                return this.suggestedproviderField;
            }
            set {
                if ((object.ReferenceEquals(this.suggestedproviderField, value) != true)) {
                    this.suggestedproviderField = value;
                    this.RaisePropertyChanged("suggestedprovider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string suggestedplan {
            get {
                return this.suggestedplanField;
            }
            set {
                if ((object.ReferenceEquals(this.suggestedplanField, value) != true)) {
                    this.suggestedplanField = value;
                    this.RaisePropertyChanged("suggestedplan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Policynumber {
            get {
                return this.PolicynumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicynumberField, value) != true)) {
                    this.PolicynumberField = value;
                    this.RaisePropertyChanged("Policynumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public bool VerificationStatus {
            get {
                return this.VerificationStatusField;
            }
            set {
                if ((this.VerificationStatusField.Equals(value) != true)) {
                    this.VerificationStatusField = value;
                    this.RaisePropertyChanged("VerificationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool addon {
            get {
                return this.addonField;
            }
            set {
                if ((this.addonField.Equals(value) != true)) {
                    this.addonField = value;
                    this.RaisePropertyChanged("addon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPaymentdata", Namespace="http://www.matontine.online:82/", ItemName="paymentdata")]
    [System.SerializableAttribute()]
    public class ArrayOfPaymentdata : System.Collections.Generic.List<MrCMS.Web.ServiceReference1.paymentdata> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="paymentdata", Namespace="http://www.matontine.online:82/")]
    [System.SerializableAttribute()]
    public partial class paymentdata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sponsoridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string beneficiaryidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string policyidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentidField;
        
        private decimal amountpaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string planpurchasedField;
        
        private System.DateTime paymentdateField;
        
        private bool addonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sponsorid {
            get {
                return this.sponsoridField;
            }
            set {
                if ((object.ReferenceEquals(this.sponsoridField, value) != true)) {
                    this.sponsoridField = value;
                    this.RaisePropertyChanged("sponsorid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string beneficiaryid {
            get {
                return this.beneficiaryidField;
            }
            set {
                if ((object.ReferenceEquals(this.beneficiaryidField, value) != true)) {
                    this.beneficiaryidField = value;
                    this.RaisePropertyChanged("beneficiaryid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string policyid {
            get {
                return this.policyidField;
            }
            set {
                if ((object.ReferenceEquals(this.policyidField, value) != true)) {
                    this.policyidField = value;
                    this.RaisePropertyChanged("policyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string paymentid {
            get {
                return this.paymentidField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentidField, value) != true)) {
                    this.paymentidField = value;
                    this.RaisePropertyChanged("paymentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal amountpaid {
            get {
                return this.amountpaidField;
            }
            set {
                if ((this.amountpaidField.Equals(value) != true)) {
                    this.amountpaidField = value;
                    this.RaisePropertyChanged("amountpaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string planpurchased {
            get {
                return this.planpurchasedField;
            }
            set {
                if ((object.ReferenceEquals(this.planpurchasedField, value) != true)) {
                    this.planpurchasedField = value;
                    this.RaisePropertyChanged("planpurchased");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime paymentdate {
            get {
                return this.paymentdateField;
            }
            set {
                if ((this.paymentdateField.Equals(value) != true)) {
                    this.paymentdateField = value;
                    this.RaisePropertyChanged("paymentdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool addon {
            get {
                return this.addonField;
            }
            set {
                if ((this.addonField.Equals(value) != true)) {
                    this.addonField = value;
                    this.RaisePropertyChanged("addon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.matontine.online:82/", ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name psponsordata from namespace http://www.matontine.online:82/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/SENDINSURDTLS", ReplyAction="*")]
        MrCMS.Web.ServiceReference1.SENDINSURDTLSResponse SENDINSURDTLS(MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/SENDINSURDTLS", ReplyAction="*")]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDINSURDTLSResponse> SENDINSURDTLSAsync(MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest request);
        
        // CODEGEN: Generating message contract since element name pbeneficiarydata from namespace http://www.matontine.online:82/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/SENDVERIFIEDBENDTLS", ReplyAction="*")]
        MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponse SENDVERIFIEDBENDTLS(MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/SENDVERIFIEDBENDTLS", ReplyAction="*")]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponse> SENDVERIFIEDBENDTLSAsync(MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest request);
        
        // CODEGEN: Generating message contract since element name RECVPAYMTDTLSResult from namespace http://www.matontine.online:82/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/RECVPAYMTDTLS", ReplyAction="*")]
        MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponse RECVPAYMTDTLS(MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/RECVPAYMTDTLS", ReplyAction="*")]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponse> RECVPAYMTDTLSAsync(MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest request);
        
        // CODEGEN: Generating message contract since element name psponsordata from namespace http://www.matontine.online:82/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/SENDPOLICYNUMBER", ReplyAction="*")]
        MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponse SENDPOLICYNUMBER(MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/SENDPOLICYNUMBER", ReplyAction="*")]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponse> SENDPOLICYNUMBERAsync(MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest request);
        
        // CODEGEN: Generating message contract since element name RECVBENDTLSResult from namespace http://www.matontine.online:82/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/RECVBENDTLS", ReplyAction="*")]
        MrCMS.Web.ServiceReference1.RECVBENDTLSResponse RECVBENDTLS(MrCMS.Web.ServiceReference1.RECVBENDTLSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/RECVBENDTLS", ReplyAction="*")]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.RECVBENDTLSResponse> RECVBENDTLSAsync(MrCMS.Web.ServiceReference1.RECVBENDTLSRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://www.matontine.online:82/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/Preauthorization", ReplyAction="*")]
        MrCMS.Web.ServiceReference1.PreauthorizationResponse Preauthorization(MrCMS.Web.ServiceReference1.PreauthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/Preauthorization", ReplyAction="*")]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.PreauthorizationResponse> PreauthorizationAsync(MrCMS.Web.ServiceReference1.PreauthorizationRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://www.matontine.online:82/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/Transaction", ReplyAction="*")]
        MrCMS.Web.ServiceReference1.TransactionResponse Transaction(MrCMS.Web.ServiceReference1.TransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.matontine.online:82/Transaction", ReplyAction="*")]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.TransactionResponse> TransactionAsync(MrCMS.Web.ServiceReference1.TransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SENDINSURDTLSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SENDINSURDTLS", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.SENDINSURDTLSRequestBody Body;
        
        public SENDINSURDTLSRequest() {
        }
        
        public SENDINSURDTLSRequest(MrCMS.Web.ServiceReference1.SENDINSURDTLSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class SENDINSURDTLSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MrCMS.Web.ServiceReference1.sponsordata psponsordata;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata;
        
        public SENDINSURDTLSRequestBody() {
        }
        
        public SENDINSURDTLSRequestBody(MrCMS.Web.ServiceReference1.sponsordata psponsordata, MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata) {
            this.psponsordata = psponsordata;
            this.plstbeneficiarydata = plstbeneficiarydata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SENDINSURDTLSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SENDINSURDTLSResponse", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.SENDINSURDTLSResponseBody Body;
        
        public SENDINSURDTLSResponse() {
        }
        
        public SENDINSURDTLSResponse(MrCMS.Web.ServiceReference1.SENDINSURDTLSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class SENDINSURDTLSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SENDINSURDTLSResult;
        
        public SENDINSURDTLSResponseBody() {
        }
        
        public SENDINSURDTLSResponseBody(string SENDINSURDTLSResult) {
            this.SENDINSURDTLSResult = SENDINSURDTLSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SENDVERIFIEDBENDTLSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SENDVERIFIEDBENDTLS", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequestBody Body;
        
        public SENDVERIFIEDBENDTLSRequest() {
        }
        
        public SENDVERIFIEDBENDTLSRequest(MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class SENDVERIFIEDBENDTLSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MrCMS.Web.ServiceReference1.beneficiarydata pbeneficiarydata;
        
        public SENDVERIFIEDBENDTLSRequestBody() {
        }
        
        public SENDVERIFIEDBENDTLSRequestBody(MrCMS.Web.ServiceReference1.beneficiarydata pbeneficiarydata) {
            this.pbeneficiarydata = pbeneficiarydata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SENDVERIFIEDBENDTLSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SENDVERIFIEDBENDTLSResponse", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponseBody Body;
        
        public SENDVERIFIEDBENDTLSResponse() {
        }
        
        public SENDVERIFIEDBENDTLSResponse(MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class SENDVERIFIEDBENDTLSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SENDVERIFIEDBENDTLSResult;
        
        public SENDVERIFIEDBENDTLSResponseBody() {
        }
        
        public SENDVERIFIEDBENDTLSResponseBody(string SENDVERIFIEDBENDTLSResult) {
            this.SENDVERIFIEDBENDTLSResult = SENDVERIFIEDBENDTLSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RECVPAYMTDTLSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RECVPAYMTDTLS", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequestBody Body;
        
        public RECVPAYMTDTLSRequest() {
        }
        
        public RECVPAYMTDTLSRequest(MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RECVPAYMTDTLSRequestBody {
        
        public RECVPAYMTDTLSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RECVPAYMTDTLSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RECVPAYMTDTLSResponse", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponseBody Body;
        
        public RECVPAYMTDTLSResponse() {
        }
        
        public RECVPAYMTDTLSResponse(MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class RECVPAYMTDTLSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MrCMS.Web.ServiceReference1.ArrayOfPaymentdata RECVPAYMTDTLSResult;
        
        public RECVPAYMTDTLSResponseBody() {
        }
        
        public RECVPAYMTDTLSResponseBody(MrCMS.Web.ServiceReference1.ArrayOfPaymentdata RECVPAYMTDTLSResult) {
            this.RECVPAYMTDTLSResult = RECVPAYMTDTLSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SENDPOLICYNUMBERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SENDPOLICYNUMBER", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequestBody Body;
        
        public SENDPOLICYNUMBERRequest() {
        }
        
        public SENDPOLICYNUMBERRequest(MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class SENDPOLICYNUMBERRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MrCMS.Web.ServiceReference1.sponsordata psponsordata;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata;
        
        public SENDPOLICYNUMBERRequestBody() {
        }
        
        public SENDPOLICYNUMBERRequestBody(MrCMS.Web.ServiceReference1.sponsordata psponsordata, MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata) {
            this.psponsordata = psponsordata;
            this.plstbeneficiarydata = plstbeneficiarydata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SENDPOLICYNUMBERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SENDPOLICYNUMBERResponse", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponseBody Body;
        
        public SENDPOLICYNUMBERResponse() {
        }
        
        public SENDPOLICYNUMBERResponse(MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class SENDPOLICYNUMBERResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SENDPOLICYNUMBERResult;
        
        public SENDPOLICYNUMBERResponseBody() {
        }
        
        public SENDPOLICYNUMBERResponseBody(string SENDPOLICYNUMBERResult) {
            this.SENDPOLICYNUMBERResult = SENDPOLICYNUMBERResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RECVBENDTLSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RECVBENDTLS", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.RECVBENDTLSRequestBody Body;
        
        public RECVBENDTLSRequest() {
        }
        
        public RECVBENDTLSRequest(MrCMS.Web.ServiceReference1.RECVBENDTLSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RECVBENDTLSRequestBody {
        
        public RECVBENDTLSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RECVBENDTLSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RECVBENDTLSResponse", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.RECVBENDTLSResponseBody Body;
        
        public RECVBENDTLSResponse() {
        }
        
        public RECVBENDTLSResponse(MrCMS.Web.ServiceReference1.RECVBENDTLSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class RECVBENDTLSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata RECVBENDTLSResult;
        
        public RECVBENDTLSResponseBody() {
        }
        
        public RECVBENDTLSResponseBody(MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata RECVBENDTLSResult) {
            this.RECVBENDTLSResult = RECVBENDTLSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreauthorizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Preauthorization", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.PreauthorizationRequestBody Body;
        
        public PreauthorizationRequest() {
        }
        
        public PreauthorizationRequest(MrCMS.Web.ServiceReference1.PreauthorizationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class PreauthorizationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public PreauthorizationRequestBody() {
        }
        
        public PreauthorizationRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreauthorizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreauthorizationResponse", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.PreauthorizationResponseBody Body;
        
        public PreauthorizationResponse() {
        }
        
        public PreauthorizationResponse(MrCMS.Web.ServiceReference1.PreauthorizationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class PreauthorizationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PreauthorizationResult;
        
        public PreauthorizationResponseBody() {
        }
        
        public PreauthorizationResponseBody(string PreauthorizationResult) {
            this.PreauthorizationResult = PreauthorizationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Transaction", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.TransactionRequestBody Body;
        
        public TransactionRequest() {
        }
        
        public TransactionRequest(MrCMS.Web.ServiceReference1.TransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class TransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public TransactionRequestBody() {
        }
        
        public TransactionRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionResponse", Namespace="http://www.matontine.online:82/", Order=0)]
        public MrCMS.Web.ServiceReference1.TransactionResponseBody Body;
        
        public TransactionResponse() {
        }
        
        public TransactionResponse(MrCMS.Web.ServiceReference1.TransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.matontine.online:82/")]
    public partial class TransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TransactionResult;
        
        public TransactionResponseBody() {
        }
        
        public TransactionResponseBody(string TransactionResult) {
            this.TransactionResult = TransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : MrCMS.Web.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<MrCMS.Web.ServiceReference1.WebServiceSoap>, MrCMS.Web.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.Web.ServiceReference1.SENDINSURDTLSResponse MrCMS.Web.ServiceReference1.WebServiceSoap.SENDINSURDTLS(MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest request) {
            return base.Channel.SENDINSURDTLS(request);
        }
        
        public string SENDINSURDTLS(MrCMS.Web.ServiceReference1.sponsordata psponsordata, MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata) {
            MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest inValue = new MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.SENDINSURDTLSRequestBody();
            inValue.Body.psponsordata = psponsordata;
            inValue.Body.plstbeneficiarydata = plstbeneficiarydata;
            MrCMS.Web.ServiceReference1.SENDINSURDTLSResponse retVal = ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).SENDINSURDTLS(inValue);
            return retVal.Body.SENDINSURDTLSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDINSURDTLSResponse> MrCMS.Web.ServiceReference1.WebServiceSoap.SENDINSURDTLSAsync(MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest request) {
            return base.Channel.SENDINSURDTLSAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDINSURDTLSResponse> SENDINSURDTLSAsync(MrCMS.Web.ServiceReference1.sponsordata psponsordata, MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata) {
            MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest inValue = new MrCMS.Web.ServiceReference1.SENDINSURDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.SENDINSURDTLSRequestBody();
            inValue.Body.psponsordata = psponsordata;
            inValue.Body.plstbeneficiarydata = plstbeneficiarydata;
            return ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).SENDINSURDTLSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponse MrCMS.Web.ServiceReference1.WebServiceSoap.SENDVERIFIEDBENDTLS(MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest request) {
            return base.Channel.SENDVERIFIEDBENDTLS(request);
        }
        
        public string SENDVERIFIEDBENDTLS(MrCMS.Web.ServiceReference1.beneficiarydata pbeneficiarydata) {
            MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest inValue = new MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequestBody();
            inValue.Body.pbeneficiarydata = pbeneficiarydata;
            MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponse retVal = ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).SENDVERIFIEDBENDTLS(inValue);
            return retVal.Body.SENDVERIFIEDBENDTLSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponse> MrCMS.Web.ServiceReference1.WebServiceSoap.SENDVERIFIEDBENDTLSAsync(MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest request) {
            return base.Channel.SENDVERIFIEDBENDTLSAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSResponse> SENDVERIFIEDBENDTLSAsync(MrCMS.Web.ServiceReference1.beneficiarydata pbeneficiarydata) {
            MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest inValue = new MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.SENDVERIFIEDBENDTLSRequestBody();
            inValue.Body.pbeneficiarydata = pbeneficiarydata;
            return ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).SENDVERIFIEDBENDTLSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponse MrCMS.Web.ServiceReference1.WebServiceSoap.RECVPAYMTDTLS(MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest request) {
            return base.Channel.RECVPAYMTDTLS(request);
        }
        
        public MrCMS.Web.ServiceReference1.ArrayOfPaymentdata RECVPAYMTDTLS() {
            MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest inValue = new MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequestBody();
            MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponse retVal = ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).RECVPAYMTDTLS(inValue);
            return retVal.Body.RECVPAYMTDTLSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponse> MrCMS.Web.ServiceReference1.WebServiceSoap.RECVPAYMTDTLSAsync(MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest request) {
            return base.Channel.RECVPAYMTDTLSAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.RECVPAYMTDTLSResponse> RECVPAYMTDTLSAsync() {
            MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest inValue = new MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.RECVPAYMTDTLSRequestBody();
            return ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).RECVPAYMTDTLSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponse MrCMS.Web.ServiceReference1.WebServiceSoap.SENDPOLICYNUMBER(MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest request) {
            return base.Channel.SENDPOLICYNUMBER(request);
        }
        
        public string SENDPOLICYNUMBER(MrCMS.Web.ServiceReference1.sponsordata psponsordata, MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata) {
            MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest inValue = new MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequestBody();
            inValue.Body.psponsordata = psponsordata;
            inValue.Body.plstbeneficiarydata = plstbeneficiarydata;
            MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponse retVal = ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).SENDPOLICYNUMBER(inValue);
            return retVal.Body.SENDPOLICYNUMBERResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponse> MrCMS.Web.ServiceReference1.WebServiceSoap.SENDPOLICYNUMBERAsync(MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest request) {
            return base.Channel.SENDPOLICYNUMBERAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERResponse> SENDPOLICYNUMBERAsync(MrCMS.Web.ServiceReference1.sponsordata psponsordata, MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata plstbeneficiarydata) {
            MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest inValue = new MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.SENDPOLICYNUMBERRequestBody();
            inValue.Body.psponsordata = psponsordata;
            inValue.Body.plstbeneficiarydata = plstbeneficiarydata;
            return ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).SENDPOLICYNUMBERAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.Web.ServiceReference1.RECVBENDTLSResponse MrCMS.Web.ServiceReference1.WebServiceSoap.RECVBENDTLS(MrCMS.Web.ServiceReference1.RECVBENDTLSRequest request) {
            return base.Channel.RECVBENDTLS(request);
        }
        
        public MrCMS.Web.ServiceReference1.ArrayOfBeneficiarydata RECVBENDTLS() {
            MrCMS.Web.ServiceReference1.RECVBENDTLSRequest inValue = new MrCMS.Web.ServiceReference1.RECVBENDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.RECVBENDTLSRequestBody();
            MrCMS.Web.ServiceReference1.RECVBENDTLSResponse retVal = ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).RECVBENDTLS(inValue);
            return retVal.Body.RECVBENDTLSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.RECVBENDTLSResponse> MrCMS.Web.ServiceReference1.WebServiceSoap.RECVBENDTLSAsync(MrCMS.Web.ServiceReference1.RECVBENDTLSRequest request) {
            return base.Channel.RECVBENDTLSAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.RECVBENDTLSResponse> RECVBENDTLSAsync() {
            MrCMS.Web.ServiceReference1.RECVBENDTLSRequest inValue = new MrCMS.Web.ServiceReference1.RECVBENDTLSRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.RECVBENDTLSRequestBody();
            return ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).RECVBENDTLSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.Web.ServiceReference1.PreauthorizationResponse MrCMS.Web.ServiceReference1.WebServiceSoap.Preauthorization(MrCMS.Web.ServiceReference1.PreauthorizationRequest request) {
            return base.Channel.Preauthorization(request);
        }
        
        public string Preauthorization(string data) {
            MrCMS.Web.ServiceReference1.PreauthorizationRequest inValue = new MrCMS.Web.ServiceReference1.PreauthorizationRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.PreauthorizationRequestBody();
            inValue.Body.data = data;
            MrCMS.Web.ServiceReference1.PreauthorizationResponse retVal = ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).Preauthorization(inValue);
            return retVal.Body.PreauthorizationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.PreauthorizationResponse> MrCMS.Web.ServiceReference1.WebServiceSoap.PreauthorizationAsync(MrCMS.Web.ServiceReference1.PreauthorizationRequest request) {
            return base.Channel.PreauthorizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.PreauthorizationResponse> PreauthorizationAsync(string data) {
            MrCMS.Web.ServiceReference1.PreauthorizationRequest inValue = new MrCMS.Web.ServiceReference1.PreauthorizationRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.PreauthorizationRequestBody();
            inValue.Body.data = data;
            return ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).PreauthorizationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MrCMS.Web.ServiceReference1.TransactionResponse MrCMS.Web.ServiceReference1.WebServiceSoap.Transaction(MrCMS.Web.ServiceReference1.TransactionRequest request) {
            return base.Channel.Transaction(request);
        }
        
        public string Transaction(string data) {
            MrCMS.Web.ServiceReference1.TransactionRequest inValue = new MrCMS.Web.ServiceReference1.TransactionRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.TransactionRequestBody();
            inValue.Body.data = data;
            MrCMS.Web.ServiceReference1.TransactionResponse retVal = ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).Transaction(inValue);
            return retVal.Body.TransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.TransactionResponse> MrCMS.Web.ServiceReference1.WebServiceSoap.TransactionAsync(MrCMS.Web.ServiceReference1.TransactionRequest request) {
            return base.Channel.TransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MrCMS.Web.ServiceReference1.TransactionResponse> TransactionAsync(string data) {
            MrCMS.Web.ServiceReference1.TransactionRequest inValue = new MrCMS.Web.ServiceReference1.TransactionRequest();
            inValue.Body = new MrCMS.Web.ServiceReference1.TransactionRequestBody();
            inValue.Body.data = data;
            return ((MrCMS.Web.ServiceReference1.WebServiceSoap)(this)).TransactionAsync(inValue);
        }
    }
}
